stages:
  fetch:
    cmd: uv run python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    params:
      - fetch.url
    outs:
      - data/raw/air/air_data.xml
    always_changed: true

  preprocess:
    cmd: uv run python src/data/preprocess_air_data.py
    deps:
      - src/data/preprocess_air_data.py
      - data/raw/air/air_data.xml
    params:
      - preprocess.output_dir
    outs:
      - data/preprocessed/air:
          persist: true

  validate:
    cmd: |
      uv run python gx/setup_ge.py
      uv run python gx/run_checkpoint.py
    deps:
      - data/preprocessed/air/
      - gx/setup_ge.py
      - gx/run_checkpoint.py
    outs:
      - gx/uncommitted/data_docs:
          persist: true
      - gx/uncommitted/validations:
          persist: true

  test_data:
    cmd: uv run python src/data/test_data.py
    deps:
      - data/preprocessed/air/
      - src/data/test_data.py
    outs:
      - data/reference/air:
          persist: true
      - reports/data_testing/air:
          persist: true