fetch:
  url: "https://www.arso.gov.si/xml/zrak/ones_zrak_urni_podatki_7dni.xml"

preprocess:
  output_dir: "data/preprocessed/air"

train:
  test_size: 72
  window_size: 24
  target_col: "PM10"
  random_state: 42
  epochs: 50
  batch_size: 32
  min_rows: 200
  mlflow_experiment: "IIS_vaje_train"
  mlflow_tracking_uri: "https://dagshub.com/poetovio/IIS_vaje.mlflow"